// Copyright 2024 k8s-crafts Authors

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// 	http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"log"
	"os"
	"text/template"

	"github.com/k8s-crafts/ephemeral-containers-plugin/pkg/version"
)

const (
	fileName    = "version_generated.go"
	ENV_VERSION = "PLUGIN_VERSION"
)

func main() {
	values := version.VersionInfo{
		Version: GetFromEnVar(ENV_VERSION, "v0.0.0-unknown"),
	}

	f, err := os.Create(fileName)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	if err = fileTemplate.Execute(f, values); err != nil {
		log.Fatal(err)
	}
}

func GetFromEnVar(key string, defaultValue string) string {
	val := os.Getenv(key)
	if len(val) > 0 {
		return val
	}
	return defaultValue
}

var fileTemplate = template.Must(template.New("").Parse(`// Code generated by version_generator.go; DO NOT EDIT.
package version

const (
	// Version of the plugin
	version string = "{{ .Version }}"
)
`))
