// MIT License

// Copyright (c) 2024 k8s-crafts Authors

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package main

import (
	"log"
	"os"
	"text/template"

	"github.com/k8s-crafts/ephemeral-containers-plugin/pkg/version"
)

const (
	fileName    = "version_generated.go"
	ENV_VERSION = "PLUGIN_VERSION"
)

func main() {
	values := version.VersionInfo{
		Version: GetFromEnVar(ENV_VERSION, "v0.0.0-unknown"),
	}

	f, err := os.Create(fileName)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	if err = fileTemplate.Execute(f, values); err != nil {
		log.Fatal(err)
	}
}

func GetFromEnVar(key string, defaultValue string) string {
	val := os.Getenv(key)
	if len(val) > 0 {
		return val
	}
	return defaultValue
}

var fileTemplate = template.Must(template.New("").Parse(`// Code generated by version_generator.go; DO NOT EDIT.
package version

const (
	// Version of the plugin
	version string = "{{ .Version }}"
)
`))
