// Code generated by version_generator.go; DO NOT EDIT.
package version

const (
	// Version of the plugin
	version string = "v1.0.0-dev"

	// The commit hash for the tagged version of the plugin
	gitCommitID string = "e4acee0095aae8aff315283cbe894f8466e5c21e-dirty"
)
