// Code generated by version_generator.go; DO NOT EDIT.
package version

const (
	// Version of the plugin
	version string = "v1.0.0-dev"

	// The commit hash for the tagged version of the plugin
	gitCommitID string = "d716bb38ef1bc934c3314f7bfc1ce485f02f77e2"
)
