// Code generated by version_generator.go; DO NOT EDIT.
package version

const (
	// Version of the plugin
	version string = "v1.0.0-dev"

	// The commit hash for the tagged version of the plugin
	gitCommitID string = "6ba5384b1260dc3324eaaf21d147688c7124e54b-dirty"
)
