name: Test

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - feature-.+
      - v[0-9]+(\.[0-9]+){0,2}
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main
      - feature-.+
      - v[0-9]+(\.[0-9]+){0,2}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22.0"
      - name: Run unit tests
        run: make test-unit
      - name: Display test coverge
        run: |
          COVERAGE=$(go tool cover -func=cover.out | grep total | awk '{print $3}'); \
          echo "## Test Coverage Summary" >> $GITHUB_STEP_SUMMARY; \
          echo "Coverage: $COVERAGE" >> $GITHUB_STEP_SUMMARY
